name: Converte e retorna em HTML

on:
  push:
    branches:
      - main
permissions:
  contents: write      

jobs:
  convert_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert TXT to HTML
      run: |
        for file in *.txt; do
          if [ -f "$file" ]; then
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            filename="${filename%.*}"
            pandoc -s "$file" -o "$filename.html"
          fi
        done

    - name: Commit and push changes to site branch
      run: |
        git checkout -b site || git checkout site
        git add .
        git commit -m "Convert TXT to HTML and send"
        git push origin HEAD:site
