name: Convert and Send HTML File

on:
  push:
    paths:
      - '**.txt' # Trigger workflow only when TXT files are pushed

jobs:
  convert_and_send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        
    - name: Convert TXT to HTML
      run: |
        for file in *.txt; do
          if [ -f "$file" ]; then
            filename=$(basename -- "$file")
            filename_without_ext="${filename%.*}"
            pandoc -s "$file" -o "$filename_without_ext.html"
          fi
        done
        
    - name: Send HTML file to destination repository
      run: |
        cp *.html Gordo2105/la.github.io
        cd Gordo2105/la.github.io
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Convert TXT to HTML and send"
        git push https://$TOKEN@github.com/Gordo2105/la.github.io.git HEAD:main
      env:
        TOKEN: ${{ secrets.token }}

