name: Copy File After Convert HTML

on:
  workflow_run:
    workflows: ["convertehtml.yml"]
    types:
      - completed

jobs:
  copy-file:
    runs-on: ubuntu-latest
    needs: convert-html
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
      with:
        source_file: 'site.html'
        destination_repo: 'Gordo2105/la.github.io'
        user_email: '1022061@alunos.ruizcosta.edu.pt'
        user_name: 'Gordo2105'
        commit_message: 'Manda pff'
