name: Mandar ficheiro HMTL

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Wait for 1 minute
      run: sleep 60

    - name: Push test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
      with:
        source_file: 'site.html'
        destination_repo: 'Gordo2105/la.github.io'
        user_email: '1022061@alunos.ruizcosta.edu.pt'
        user_name: 'Gordo2105'
        commit_message: 'Manda pff'
