name: Send HTML Files to Site Branch

on:
  push:
    branches:
      - main

jobs:
  send_to_site_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Move HTML files to site branch
      run: |
        mkdir -p site
        mv *.html site/
        
    - name: Commit and push changes to site branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b site
        git add site/*
        git commit -m "Add HTML files to site branch"
        git push origin site
