name: Verify and Send HTML File

on:
  push:
    paths:
      - '**.html' # Trigger workflow only when HTML files are pushed

jobs:
  verify_and_send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Verify if file is HTML
      run: |
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "File $file is HTML."
          else
            echo "File $file is not HTML."
            exit 1
          fi
        done

    - name: Send HTML file to destination repository
      run: |
        cp *.html destination-repo/
        cd destination-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add HTML file"
        git push https://$TOKEN@github.com/Gordo2105/la.github.io.git HEAD:main
      env:
        TOKEN: ${{ secrets.token }}
