name: Notifica ntfy.sh quando acontece push

on:
  push:
    paths:
      - '**/*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notifica ntfy.sh
        env:
          NTFY_URL: ntfy.sh/gordoromano
          MESSAGE: 'Foram efetuadas alterações'
        run: |
          curl -X POST -H "Title: Github" -H "Tags:skull" -H "Priority: urgent" -d "$MESSAGE" $NTFY_URL
