name: Notify ntfy.sh on file push

on:
  push:
    paths:
      - '**/*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify ntfy.sh
        env:
          NTFY_URL: ntfy.sh/gordoromano
          MESSAGE: 'Foram efetuadas alterações'
        run: |
          curl -X POST -H "Title: Github" -H "Tags:skull" -H "Priority: max" -d "$MESSAGE" $NTFY_URL
